=== Bo0TSk1n/labs/Лаба 7-10/lab7-10/lab8.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="stop">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:integer" name="id"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="time" type="xs:time"/>

  <xs:element name="price" type="xs:decimal"/>

  <xs:element name="free" type="xs:integer"/>

  <xs:element name="tour">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="time"/>
        <xs:element ref="price"/>
        <xs:element ref="free"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="to">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:integer" name="id"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="stops">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element ref="stop" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="date" type="xs:date"/>

  <xs:element name="tours">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tour" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="bus">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="to"/>
        <xs:element ref="stops"/>
        <xs:element ref="date"/>
        <xs:element ref="tours"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="schedule">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="bus" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Bo0TSk1n/labs/Лаба 1/lab7-10/lab7.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE schedule [
        <!ELEMENT schedule (bus)*>
        <!ELEMENT bus (to|stops|date|tours)*>
        <!ELEMENT to (#PCDATA)>
        <!ATTLIST to
                id CDATA #REQUIRED>
        <!ELEMENT stops (stop)*>
        <!ELEMENT stop (#PCDATA)>
        <!ATTLIST stop
                id CDATA #REQUIRED>
        <!ELEMENT date (#PCDATA)>
        <!ELEMENT tours (tour)*>
        <!ELEMENT tour (time|price|free)*>
        <!ELEMENT time (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
        <!ELEMENT free (#PCDATA)>
        ]>
<schedule  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="lab8.xsd">
    <bus>
        <to id="1">Киев</to>
        <stops>
            <stop id="102">Кировоград</stop>
            <stop id="104">Черкассы</stop>
        </stops>
        <date>2020-06-28</date>
        <tours>
            <tour>
                <time>06:00:00</time>
                <price>120.00</price>
                <free>8</free>
            </tour>
            <tour>
                <time>12:00:00</time>
                <price>80.40</price>
                <free>36</free>
            </tour>
        </tours>
    </bus>
        <bus>
        <to id="104">Черкассы</to>
        <stops>
            <stop id="102">Кировоград</stop>
        </stops>
        <date>2020-06-28</date>
        <tours>
            <tour>
                <time>06:00:00</time>
                <price>80.25</price>
                <free>8</free>
            </tour>
            <tour>
                <time>12:00:00</time>
                <price>60.25</price>
                <free>36</free>
            </tour>
        </tours>
    </bus>
    <bus>
        <to id="104">Одесса</to>
        <stops>

        </stops>
        <date>2020-06-30</date>
        <tours>
            <tour>
                <time>05:00:00</time>
                <price>100.00</price>
                <free>22</free>
            </tour>
        </tours>
    </bus>
     <bus>
        <to id="160">Львов</to>
        <stops>
            <stop id="102">Кировоград</stop>
            <stop id="140">Умань</stop>
            <stop id="144">Винница</stop>
            <stop id="156">Хмельницкий</stop>
            <stop id="158">Тернополь</stop>
        </stops>
        <date>2020-06-24</date>
        <tours>
            <tour>
                <time>16:00:00</time>
                <price>320.20</price>
                <free>20</free>
            </tour>
            <tour>
                <time>20:00:00</time>
                <price>280.00</price>
                <free>48</free>
            </tour>
        </tours>
    </bus>
    <bus>
        <to id="144">Винница</to>
        <stops>
            <stop id="102">Кировоград</stop>
            <stop id="140">Умань</stop>
        </stops>
        <date>2020-06-24</date>
        <tours>
            <tour>
                <time>16:00:00</time>
                <price>180.00</price>
                <free>20</free>
            </tour>
            <tour>
                <time>20:00:00</time>
                <price>160.80</price>
                <free>48</free>
            </tour>
        </tours>
    </bus>
</schedule>
